### PR TITLE
Add clicker support. Tested with Logitech R800

### PR DESCRIPTION
**Pull request by dkundel**
Added clicker support for @yoshuawuyts talk at the Node.js Berlin meetup. I also added quitting the presentation by pressing <kbd>Esc</kbd> which is equivalent to pressing the Start/End presentation button on the clicker.

Mappings added:
<kbd>Esc</kbd> -> Quit presentation
<kbd>Page Up</kbd> -> Previous slide
<kbd>Page Down</kbd> -> Next slide

### CODE REVIEW

**Comment by hackergrrl** [comment]
Awesome work! :star2:

Could you also add a note to the README (maybe somewhere under **Usage**) that mentions that the Logitech R800 works out-of-the-box?

**Comment by dkundel** [comment]
Updated the README 🙂

**Comment by dkundel** [comment]
Updated the README 🙂

**Comment by yoshuawuyts** [comment]
hahahaha, tnx for turning this into a pr :tada:

**Comment by hackergrrl** [comment]
Woohoo! Thank you @dkundel!

**Comment by hackergrrl** [comment]
Added to `1.5.0`.

**Comment by dkundel** [comment]
Wohoo 🎊 thanks!

**Pull request merged**
