### PR TITLE
Add images support

### PR DESCRIPTION
**Pull request by rafaelrinaldi**
This PR adds image support to slides (thanks to [iTerm](https://www.iterm2.com/images.html)).

``` md
# Images

![ron](ron.png)

Ron Swanson and his ice cream

![pizza](pizza.png)

There's anything a pizza can't solve
```

demo
## Notes
- Will parse markdown images (does not support HTML image tags)
- Will do nothing if terminal does not support images (currently a simple check to `TERM_PROGRAM` to figure it out)
- Add `images` option which is `true` by default (let me know if it should be `false` by default)
- User can turn off images with `--no-images`

---

Let me know if PR looks good. I can make any adjustments if needed.

### CODE REVIEW

**Comment by dominictarr** [comment]
cool, my terminal (on linux doesn't support this) but it doesn't do anything weird, so I'll merge.
can you add an example image to the readme so that all tslide features are demonstrated via the readme?

**Comment by rafaelrinaldi** [comment]
@dominictarr Done. What do you think?

**Comment by dominictarr** [comment]
that image doesn't display in github, I think you need to use an relative link, and check it into the repo.
Also, especially, you could you put the embedded image in image section?

**Comment by rafaelrinaldi** [comment]
@dominictarr Done.

**Comment by dominictarr** [comment]
you are missing screenshot.png

**Comment by rafaelrinaldi** [comment]
@dominictarr That's not needed anymore. See: https://github.com/rafaelrinaldi/tslide/tree/feat/images

**Comment by dominictarr** [comment]
okay, just one more thing: this currently loads files relative to the cwd (i think, can't test) but pretty sure that is what happens when you do `fs.readFileSync(filename)`

Of course, the filenames should be relative to the md file, so it should be `dir=path.dirname(input); fs.readFileSync(path.join(dir, filename))`

otherwise, you can't do `tslide ../README.md`

**Comment by rafaelrinaldi** [comment]
@dominictarr Good catch. Fixed too.

**Pull request merged**
