### PR TITLE
acknowledge tslide contributors

### PR DESCRIPTION
**Pull request by dominictarr**
and also tidy up readme, I noticed that there where some misplaced `---`
this makes the readme work right as a tslide presentation.

and link to xslide (are there any other tsilde compatible viewers?)

### CODE REVIEW

**Comment by loklaan** [comment]
:smile: awesome - so nice

**Comment by hackergrrl** [comment]
LGTM

(Nitpick on the mixing of some headings being capitalized and others not.)

**Comment by rafaelrinaldi** [comment]
s2

**Comment by dominictarr** [comment]
merged into 1.4.1!

**Pull request merged**
