### PR TITLE
usage message + bugfix when using tslide in a pipe

### PR DESCRIPTION
**Pull request by hackergrrl**

### CODE REVIEW

**Comment by rafaelrinaldi** [comment]
@noffle no code review? 😢

**Comment by hackergrrl** [comment]
You're right! I'm a villain. Please feel free to CR retroactively -- happy
to make revisions or push an emergency fix if I've goofed anything.

**Comment by rafaelrinaldi** [comment]
@noffle NP man, just feel free to use my help whenever you want 👍

**Comment by hackergrrl** [comment]
I will! Really happy this thing has such interest behind it.

**Pull request merged**
